server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
  ssl:
    key-alias: tomcat
    key-store: /etc/letsencrypt/live/vegardaaberge.no/keystore.p12
    key-store-type: pkcs12
    key-store-password: insert_password
    key-password: insert_password

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/playgroup
    username: superuser
    password: insert_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

document:
  upload-directory: uploads
  profile-directory: uploads/profile

playgroup:
  app:
    jwtSecret: add_secret_text